# -*- coding: utf-8 -*-
"""aead.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cJSaKKPS4_N_zzVHla_mgnIh7oBs2oVw
"""

import pandas as pd
from koeda import AEDA

def apply_aeda(df):
    # AEDA 적용
    aeda = AEDA(
        morpheme_analyzer="Okt",  # Default = "Okt"
        punc_ratio=0.3
    )

    # 결과를 담을 리스트 생성
    result = []

    for sentence in df['sentence']:
        augmented_sentence = aeda(sentence)
        result.append(augmented_sentence)

    return result

if __name__ == "__main__":
    # 텍스트 데이터 로드
    split_voicephishing = pd.read_csv("split_voicephishing.csv")

    # AEDA 적용
    result = apply_aeda(split_voicephishing)

    # 결과를 데이터프레임으로 변환
    result_df = pd.DataFrame({'sentence': result})

    # CSV 파일로 저장
    result_df.to_csv("aead_voicephishing.csv", index=False)