# -*- coding: utf-8 -*-
"""back_translation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14WezJGyK-aVUyfprIHNe29U3KqOXQi0f
"""

import pandas as pd
from ktextaug import TextAugmentation

if __name__ == "__main__":
    # CSV 파일 경로
    csv_file = "split_voicephishing.csv"

    # CSV 파일을 읽어서 데이터프레임으로 저장
    split_voicephishing = pd.read_csv(csv_file)

    # 문장 리스트 생성
    sentences = split_voicephishing['sentence'].tolist()

    # TextAugmentation 객체 생성
    agent = TextAugmentation(num_processes=1)

    # 백 번역 수행
    back_translate = agent.generate(sentences, mode="back_translate", target_language='ja')

    # 결과를 데이터프레임으로 변환
    back_translate_df = pd.DataFrame({'sentence': back_translate})

    # CSV 파일로 저장
    back_translate_df.to_csv("back_translate123.csv", index=False)