# -*- coding: utf-8 -*-
"""KSS

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ONrmJMTdAjCEUmKU2R4Qlu8Jmfp3wU3Q
"""

import kss
import pandas as pd

def preprocess_transcript(df):
    df['transcript'] = df['transcript'].fillna('').astype(str)

    # 분리된 문장을 저장할 리스트 생성
    sentences = []

    for text in df['transcript']:
        splitted_sentences = kss.split_sentences(text)
        sentences.extend(splitted_sentences)

    # 분리된 문장을 새로운 데이터프레임으로 저장
    split_df = pd.DataFrame({'sentence': sentences})
    split_df['sentence'] = split_df['sentence'].fillna('').astype(str)

    return split_df

def save_to_csv(df, output_csv_file):
    df.to_csv(output_csv_file, index=False)  # index=False를 지정하여 인덱스를 저장하지 않습니다.
    print("Sentences saved to:", output_csv_file)

if __name__ == "__main__":
    # 이하 실행 코드
    # 예시 데이터프레임 생성
    voice_phishing = pd.DataFrame({'transcript': ['문장1. 문장2.', '문장3.']})

    # 전처리 함수 호출
    split_voicephishing = preprocess_transcript(voice_phishing)

    # CSV로 저장
    output_csv_file = "split_voicephishing.csv"
    save_to_csv(split_voicephishing, output_csv_file)